### ISSUE TITLE
Main build is broken

### ISSUE THREAD

**Issue by sapsan4eg** [MarcinMoskala/KotlinAcademyApp#40]
Hey, after your commit 24559d36c8cbe6150a0cb42b1ebe6f1f5e716c91 'Introduce coroutines to common-client module' the main build stopped working.
To reproduce this bug, on master branch just run: `./gradlew build`.
Gradle cannot find the kotlinx `common-client/src/main/kotlin/org/kotlinacademy/presentation/BasePresenter.kt: (3, 8): Unresolved reference: kotlinx
`
Separately, the project is built and started normally. But this is a very annoying mistake that is misleading.

**Comment by lex-em** [comment]
Hi, can it be fixed?
