### ISSUE TITLE
Missing Some Files while Downloading

### ISSUE THREAD

**Issue by pratikbutani** [MarcinMoskala/KotlinAcademyApp#5]
I didn't found **presenter** package in this [mobile package](https://github.com/MarcinMoskala/KotlinAcademyApp/tree/master/android/mobile/src/main/java/org/kotlinacademy/mobile)

I did't found following in [FirebaseIdService.kt](https://github.com/MarcinMoskala/KotlinAcademyApp/blob/master/android/mobile/src/main/java/org/kotlinacademy/mobile/view/notifications/FirebaseIdService.kt#L7): 
```
import org.kotlinacademy.data.FirebaseTokenType.Android
import org.kotlinacademy.presentation.notifications.RegisterNotificationTokenPresenter
import org.kotlinacademy.presentation.notifications.RegisterNotificationTokenView
```

Is there any solution?

**Comment by MarcinMoskala** [comment]
These files are in `common-client`:

https://github.com/MarcinMoskala/KotlinAcademyApp/blob/master/common-client/src/main/kotlin/org/kotlinacademy/presentation/notifications/RegisterNotificationTokenView.kt

I think that the reason why you have this error is that you don't use Kotlin version that supports multiplatform development (1.2). Here are steps how to set it:

![selection_239](https://user-images.githubusercontent.com/6850787/33895508-f4a3d720-df60-11e7-9d64-9b7e9adbaaf8.png)

![configure kotlin plugin updates_241](https://user-images.githubusercontent.com/6850787/33895574-16c2cbe0-df61-11e7-82a7-fd8121b4720d.png)

Check for updates and click ok. Then restart AS and it should work fine. Please, tell me if it helped.
